### ISSUE TITLE
issues proposing a zdt migration

### ISSUE THREAD

**Issue by jchappelow** [kwilteam/kwil-db#1003]
We recently migrated our staging network using a zdt migration to a new network.

Today I was going to migrate back, so on the one node of the current network, i did:

```
kwil-admin migrate propose -a 50 -c kwil-chain-18 -d 1200
```

```
2024-09-19T19:10:59.931Z        info    kwild.cometbft  finalizing commit of block      {"module": "consensus", "height": 184141, "hash": "4BB67D62063E9E80899A81C07D12E5342FF58E0191168C9902FC356420D82CF6", "root": "B184DB8C62C75AF8F32F3EC9F32736EE88841EDC4A4A79447D04AAC8FF826C7F", "num_txs": 1}                                                                   
2024-09-19T19:10:59.94Z debug   kwild.txapp     executing transaction   {"tx": {"signature":{"sig":"gS4bYxPjZ9dsbyfzPWSVCKXAEI2lcKQAEJsIzdw7mmhpkAl4G7RjBHcj9CfFRqyPARO+GvE1tU1sMgmOwPadBA==","type":"ed25519"},"body":{"desc":"","payload":"AAHh4IltaWdyYXRpb26VAAHSMoIEsI1rd2lsLWNoYWluLTE4","type":"create_resolution","fee":"21000","nonce":481,"chain_id":"kwil-chain-16"},"serialization":"concat","sender":"997ccd99f95ae68327609938b62201caad61227bb3c5e04e0bedf529d5e306c9"}}                                                                         
2024-09-19T19:10:59.944Z        debug   kwild.event-broadcaster local node is current block proposer, skipping voteID broadcast                                                      
2024-09-19T19:10:59.944Z        debug   kwild.abci      Finalize(start) {"height": 184140, "appHash": "b184db8c62c75af8f32f3ec9f32736ee88841edc4a4a79447d04aac8ff826c7f"}            
2024-09-19T19:10:59.946Z        debug   kwild.txapp     resolving resolution    {"type": "migration", "id": "5a343b97-0e6b-52c2-8758-37b76f306c55"}                                  
2024-09-19T19:10:59.947Z        warn    kwild.txapp     error resolving resolution      {"type": "migration", "id": "5a343b97-0e6b-52c2-8758-37b76f306c55", "error": "rlp: too few elements for migrations.MigrationDeclaration"} 
```

the migration resolution failed with `error resolving resolution      {"type": "migration", "id": "5a343b97-0e6b-52c2-8758-37b76f306c55", "error": "rlp: too few elements for migrations.MigrationDeclaration"}`

Presumably this was because the `Timestamp` field was added in https://github.com/kwilteam/kwil-db/commit/ba6e3ea170e904ea7eb289f1cf83eb98c3e15d13#diff-10dfd08b2d75451c983f4fb984b9043d212f117bbe39c241efda2b429f41ddf9R91

I did not immediately notice this, but when I tried to get the genesis-state for the migration:

```
$  kwil-admin migrate genesis-state --root-dir ~/migrate-genesis
No genesis state to download yet. Migration is set to start at block height: 0
```

So a side issue is that that is confusing.  There should be a "no migration set to start" or something

```
$  kwil-admin migrate list
No migrations found.
```

Even bigger issue after re-trying the same `migrate propose` command (`CONSENSUS FAILURE!!!`):

```
2024-09-19T19:13:42.668Z        info    kwild.cometbft  finalizing commit of block      {"module": "consensus", "height": 184168, "hash": "1C52ECC3F2CCB93B23F8178D08673F93F09C9FC325
2D141D52D71AD8141DD7E1", "root": "FAA3DF0D93307F55A99B767F9AC8FF18A35750046EE73F401445BC0A3AE9DC73", "num_txs": 1}                                                                   
2024-09-19T19:13:42.677Z        debug   kwild.txapp     executing transaction   {"tx": {"signature":{"sig":"0C/KUr+z10Xq7p32nNM0UumSVHkurWtHr4antowcsPfyd3hVRgYqcs5EyaTp8P19JHLdDHKl8
Rz3AP7LA7blBg==","type":"ed25519"},"body":{"desc":"","payload":"AAHh4IltaWdyYXRpb26VAAHSMoIEsI1rd2lsLWNoYWluLTE4","type":"create_resolution","fee":"21000","nonce":482,"chain_id":"kw
il-chain-16"},"serialization":"concat","sender":"997ccd99f95ae68327609938b62201caad61227bb3c5e04e0bedf529d5e306c9"}}                                                                 
2024-09-19T19:13:42.68Z debug   kwild.event-broadcaster local node is current block proposer, skipping voteID broadcast                                                              
2024-09-19T19:13:42.68Z debug   kwild.abci      Finalize(start) {"height": 184167, "appHash": "faa3df0d93307f55a99b767f9ac8ff18a35750046ee73f401445bc0a3ae9dc73"}                    
2024-09-19T19:13:42.682Z        debug   kwild.txapp     resolving resolution    {"type": "migration", "id": "5a343b97-0e6b-52c2-8758-37b76f306c55"}                                  
2024-09-19T19:13:42.682Z        warn    kwild.txapp     error resolving resolution      {"type": "migration", "id": "5a343b97-0e6b-52c2-8758-37b76f306c55", "error": "rlp: too few el
ements for migrations.MigrationDeclaration"}                                                                                                                                         
2024-09-19T19:13:42.683Z        warn    kwild.pg        ERROR [23505]: duplicate key value violates unique constraint "processed_pkey" / Key (id)=(\x5a343b970e6b52c2875837b76f306c55
) already exists.                                                                                                                                                                    
2024-09-19T19:13:42.685Z        warn    kwild.pg        ERROR [25P02]: current transaction is aborted, commands ignored until end of transaction block                               
2024-09-19T19:13:42.685Z        error   kwild.cometbft  error in proxyAppConn.FinalizeBlock     {"module": "state", "err": "failed to finalize transaction app: ERROR: duplicate key 
value violates unique constraint \"processed_pkey\" (SQLSTATE 23505)", "goversion": "go1.23.1", "mod_version": "(devel)", "revision": "852df6a34cb14c9cb43e6bfb2f8e087cf6154798", "bu
ild_time": "2024-09-18T22:40:07Z"}                                                                                                                                                   
2024-09-19T19:13:42.685Z        error   kwild.cometbft  CONSENSUS FAILURE!!!    {"module": "consensus", "err": "failed to apply block; error failed to finalize transaction app: ERRO
R: duplicate key value violates unique constraint \"processed_pkey\" (SQLSTATE 23505)", "stack": "goroutine 381 [running]:\nruntime/debug.Stack()\n\t/home/ubuntu/go123/src/runtime/d
ebug/stack.go:26 +0x5e\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()\n\t/data/gopath/pkg/mod/github.com/cometbft/cometbft@v0.38.12/consensus/state.go:801 +
0x46\npanic({0x15869e0?, 0xc000869d50?})\n\t/home/ubuntu/go123/src/runtime/panic.go:785 +0x132\ngithub.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0xc000b5d508, 0x2cf68)
\n\t/data/gopath/pkg/mod/github.com/cometbft/cometbft@v0.38.12/consensus/state.go:1781 +0xde5\ngithub.com/cometbft/cometbft/consensus.(*State).tryFinalizeCommit(0xc000b5d508, 0x2cf6
8)\n\t/data/gopath/pkg/mod/github.com/cometbft/cometbft@v0.38.12/consensus/state.go:1682 +0x2e8\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit.func1()\n\t/data/gopath/
pkg/mod/github.com/cometbft/cometbft@v0.38.12/consensus/state.go:1617 +0x9c\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit(0xc000b5d508, 0x2cf68, 0x0)\n\t/data/gopath/
pkg/mod/github.com/cometbft/cometbft@v0.38.12/consensus/state.go:1655 +0xc2f\ngithub.com/cometbft/cometbft/consensus.(*State).addVote(0xc000b5d508, 0xc009b9ca90, {0x0, 0x0})\n\t/dat
a/gopath/pkg/mod/github.com/cometbft/cometbft@v0.38.12/consensus/state.go:2335 +0x1c6d\ngithub.com/cometbft/cometbft/consensus.(*State).tryAddVote(0xc000b5d508, 0xc009b9ca90, {0x0?,
 0x490ace?})\n\t/data/gopath/pkg/mod/github.com/cometbft/cometbft@v0.38.12/consensus/state.go:2067 +0x26\ngithub.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc000b5d508, {{0
x1bd9560, 0xc000b0db80}, {0x0, 0x0}})\n\t/data/gopath/pkg/mod/github.com/cometbft/cometbft@v0.38.12/consensus/state.go:929 +0x38b\ngithub.com/cometbft/cometbft/consensus.(*State).re
ceiveRoutine(0xc000b5d508, 0x0)\n\t/data/gopath/pkg/mod/github.com/cometbft/cometbft@v0.38.12/consensus/state.go:856 +0x4f9\ncreated by github.com/cometbft/cometbft/consensus.(*Stat
e).OnStart in goroutine 405\n\t/data/gopath/pkg/mod/github.com/cometbft/cometbft@v0.38.12/consensus/state.go:398 +0x10c\n", "goversion": "go1.23.1", "mod_version": "(devel)", "revis
ion": "852df6a34cb14c9cb43e6bfb2f8e087cf6154798", "build_time": "2024-09-18T22:40:07Z"}   

```

**Comment by jchappelow** [comment]
I think it was still "marked" processed the first time even thought the resolve func failed.

```
markManyProcessed = `INSERT INTO ` + votingSchemaName + `.processed (id) SELECT unnest($1::BYTEA[]);`
```

**Comment by jchappelow** [comment]
Probably the `range finalized` and `range resolveFuncs` loops should be merged, only appending to the IDs slices if the resolve func succeeded?

**Comment by jchappelow** [comment]
Old `kwil-admin` caused the bad migration payload.
But we still need to handle failed ResolveFuncs correctly and prevent consensus failure in this case.

**Comment by jchappelow** [comment]
Also worth noting that we should not rely on the payloads to create unique resolution IDs.  A user/operator setting the timestamp to zero or an already-used timestamp is out of our control, and the node needs to be robust to that.

**Comment by jchappelow** [comment]
> Probably the `range finalized` and `range resolveFuncs` loops should be merged, only appending to the IDs slices if the resolve func succeeded?

@charithabandi sounds like we can't do this due to comments there about power updates and balance and such.

About the processed table already having this resolution, does `processVotes` need a call to `voting.FilterNotProcessed` to ensure we don't try to run resolv funcs for already processed IDs?  I'm also wondering about `GetResolutionsByThresholdAndType`... should that not returns ones that are already processed?  I really don't know.

**Comment by charithabandi** [comment]
#974 fixes this
