### ISSUE TITLE
failed to build event store: ERROR: duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by jchappelow** [kwilteam/kwil-db#786]
Starting up a node on staging network:

```
panic while building kwild: failed to build event store: ERROR: duplicate key value violates unique constraint "resolution_types_name_key" (SQLSTATE 23505)

stack:

goroutine 1 [running]:
github.com/kwilteam/kwil-db/cmd/kwild/server.New.func1()
        /home/ubuntu/kwil/git/kwil-db/cmd/kwild/server/server.go:76 +0x24d
panic({0x171d480?, 0xc000600c80?})
        /home/ubuntu/go122/src/runtime/panic.go:770 +0x132
github.com/kwilteam/kwil-db/cmd/kwild/server.failBuild(...)
        /home/ubuntu/kwil/git/kwil-db/cmd/kwild/server/build.go:908
github.com/kwilteam/kwil-db/cmd/kwild/server.buildEventStore(0xc0000a8300, 0xc0006000a0)
        /home/ubuntu/kwil/git/kwil-db/cmd/kwild/server/build.go:394 +0x1a5
github.com/kwilteam/kwil-db/cmd/kwild/server.buildServer(0xc0000a8300, 0xc0006000a0)
        /home/ubuntu/kwil/git/kwil-db/cmd/kwild/server/build.go:178 +0x85
github.com/kwilteam/kwil-db/cmd/kwild/server.New({0x1b915e8, 0xc000100460}, 0xc0001f6b70, 0xc000169c00, 0xc00011bd10, 0x0)
        /home/ubuntu/kwil/git/kwil-db/cmd/kwild/server/server.go:115 +0xa09
github.com/kwilteam/kwil-db/cmd/kwild/root.RootCmd.func1(0xc0002d1508, {0xc0001f9980?, 0x7?, 0x1839c98?})
        /home/ubuntu/kwil/git/kwil-db/cmd/kwild/root/root.go:78 +0x43f
github.com/spf13/cobra.(*Command).execute(0xc0002d1508, {0xc000112640, 0x2, 0x2})
        /data/gopath/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002d1508)
        /data/gopath/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0x0?)
        /data/gopath/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039 +0x13
main.main()
        /home/ubuntu/kwil/git/kwil-db/cmd/kwild/main.go:11 +0x18
```

This was on a clean git pull (fast forward) of `main`:  `ed2c974b..cdba4b01  main                -> origin/main`
https://github.com/kwilteam/kwil-db/compare/ed2c974b...cdba4b01

Is there something on this diff that would make this expected?

I vaguely recall some change with how resolutions are registered.  @charithabandi @brennanjl ?

**Comment by jchappelow** [comment]
I think we figured it out, and some related improvements to make

> conflict_target
> 
>     Specifies which conflicts ON CONFLICT takes the alternative action on by choosing arbiter indexes. Either performs unique index inference, or names a constraint explicitly. For ON CONFLICT DO NOTHING, it is optional to specify a conflict_target; **when omitted, conflicts with all usable constraints (and unique indexes) are handled**. For ON CONFLICT DO UPDATE, a conflict_target must be provided.

Emphasis above added by me is the issue for this insert. 

Possibly resolutions are to omit the `conflict_target` so it effectively captures both constraints (the one on `id` and the one on `name`), or to remove the `unique` on the `name` column since there is a one-to-one mapping from `name` to `id`, which should make the unique constraint on `id` sufficient.

There seem to be a number of other tables where we insert with `ON CONFLICT` for only `id` but not another derived column that would also violate.  Worth auditing all.
