### ISSUE TITLE
action view_by_range: interface conversion: interface {} is *parse.ExpressionVariable, not *parse.ExpressionLiteral

### ISSUE THREAD

**Issue by jchappelow** [kwilteam/kwil-db#809]
After rebuilding with https://github.com/kwilteam/kwil-db/pull/807, which contains the fix for yesterday's migration error (`panic while building kwild: failed to build engine: action check_balance: (action) type error: procedure does not return any value`), I retried starting up v0.8 again, which has just finished importing genesis state from v0.7.

The new error is: `action view_by_range: interface conversion: interface {} is *parse.ExpressionVariable, not *parse.ExpressionLiteral`

```
Error: panic while building kwild: failed to build engine: action view_by_range: interface conversion: interface {} is *parse.ExpressionVariable, not *parse.ExpressionLiteral

goroutine 1 [running]:
github.com/kwilteam/kwil-db/parse.setupParser.func1({0x161e4a0?, 0xc000a0fb30?})
	/home/jon/kwil/git/kwil-db/parse/parse.go:433 +0xa5
github.com/kwilteam/kwil-db/parse.analyzeActionAST.func1()
	/home/jon/kwil/git/kwil-db/parse/parse.go:350 +0x34
panic({0x161e4a0?, 0xc000a0fb30?})
	/home/jon/go122/src/runtime/panic.go:770 +0x132
github.com/kwilteam/kwil-db/parse.(*schemaVisitor).VisitSelect_statement(0xc000a0ea80, 0xc0004c5220)
	/home/jon/kwil/git/kwil-db/parse/antlr.go:923 +0x4c8
github.com/kwilteam/kwil-db/parse/gen.(*Select_statementContext).Accept(0xc0004c5220, {0x1bbdd08?, 0xc000a0ea80})
	/home/jon/kwil/git/kwil-db/parse/gen/kuneiform_parser.go:8400 +0x117
github.com/kwilteam/kwil-db/parse.(*schemaVisitor).VisitSql_statement(0xc000a0ea80, 0xc00050c480)
	/home/jon/kwil/git/kwil-db/parse/antlr.go:872 +0xdde
github.com/kwilteam/kwil-db/parse/gen.(*Sql_statementContext).Accept(0xc00050c480, {0x1bbdd08?, 0xc000a0ea80})
	/home/jon/kwil/git/kwil-db/parse/gen/kuneiform_parser.go:7740 +0x117
github.com/kwilteam/kwil-db/parse.(*schemaVisitor).VisitSql_action(0xc000a0ea80, 0xc00050c400)
	/home/jon/kwil/git/kwil-db/parse/antlr.go:1605 +0xa7
github.com/kwilteam/kwil-db/parse/gen.(*Sql_actionContext).Accept(0xc00050c400, {0x1bbdd08?, 0xc000a0ea80})
	/home/jon/kwil/git/kwil-db/parse/gen/kuneiform_parser.go:15889 +0x117
github.com/kwilteam/kwil-db/parse.(*schemaVisitor).VisitAction_block(0xc000a0ea80, 0x185d1c0?)
	/home/jon/kwil/git/kwil-db/parse/antlr.go:1597 +0x8d
github.com/kwilteam/kwil-db/parse/gen.(*Action_blockContext).Accept(0xc00050c300, {0x1bbdd08?, 0xc000a0ea80})
	/home/jon/kwil/git/kwil-db/parse/gen/kuneiform_parser.go:15603 +0x114
github.com/kwilteam/kwil-db/parse.(*schemaVisitor).VisitAction_entry(0xc000a0ea80, 0x185d1c0?)
	/home/jon/kwil/git/kwil-db/parse/antlr.go:74 +0x9b
github.com/kwilteam/kwil-db/parse/gen.(*Action_entryContext).Accept(0xc00050c280, {0x1bbdd08?, 0xc000a0ea80})
	/home/jon/kwil/git/kwil-db/parse/gen/kuneiform_parser.go:1179 +0x114
github.com/kwilteam/kwil-db/parse.analyzeActionAST(0xc00002eb60, 0xc0003f7c20, {0x0, 0x0, 0x0})
	/home/jon/kwil/git/kwil-db/parse/parse.go:358 +0x273
github.com/kwilteam/kwil-db/parse.ParseAction(...)
	/home/jon/kwil/git/kwil-db/parse/parse.go:336
github.com/kwilteam/kwil-db/internal/engine/generate.GenerateActionBody(0xc00043d2f8?, 0x1860db6?, {0xc000a1b7c0, 0x3c})
	/home/jon/kwil/git/kwil-db/internal/engine/generate/actions.go:87 +0x9f
github.com/kwilteam/kwil-db/internal/engine/execution.prepareActions(0xc0003f7c20)
	/home/jon/kwil/git/kwil-db/internal/engine/execution/procedure.go:86 +0x14f
github.com/kwilteam/kwil-db/internal/engine/execution.(*GlobalContext).loadDataset(0xc000908810, {0x1bbcc60, 0xc000140050}, 0xc0003f7c20)
	/home/jon/kwil/git/kwil-db/internal/engine/execution/global.go:401 +0x169
github.com/kwilteam/kwil-db/internal/engine/execution.NewGlobalContext({0x1bbcc60, 0xc000140050}, {0x756c8d9003c8, 0xc0007e21f8}, 0xc000908510, 0xc0009087b0)
	/home/jon/kwil/git/kwil-db/internal/engine/execution/global.go:158 +0x11a
github.com/kwilteam/kwil-db/cmd/kwild/server.buildEngine(0xc0000d0ae0, 0xc0006d6480)
	/home/jon/kwil/git/kwil-db/cmd/kwild/server/build.go:522 +0x498
github.com/kwilteam/kwil-db/cmd/kwild/server.buildServer(0xc0000d0ae0, 0xc0005e0060)
	/home/jon/kwil/git/kwil-db/cmd/kwild/server/build.go:176 +0x68
github.com/kwilteam/kwil-db/cmd/kwild/server.New({0x1bbcc60, 0xc000140050}, 0xc0003a86c0, 0xc00042b180, 0xc000516378, 0x0)
	/home/jon/kwil/git/kwil-db/cmd/kwild/server/server.go:120 +0xa09
github.com/kwilteam/kwil-db/cmd/kwild/root.RootCmd.func1(0xc00027a308, {0xc000157060?, 0x7?, 0x18613d2?})
	/home/jon/kwil/git/kwil-db/cmd/kwild/root/root.go:92 +0x573
github.com/spf13/cobra.(*Command).execute(0xc00027a308, {0xc000052520, 0x2, 0x2})
	/home/jon/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc00027a308)
	/home/jon/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0xc0000061c0?)
	/home/jon/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039 +0x13
main.main()
	/home/jon/kwil/git/kwil-db/cmd/kwild/main.go:10 +0x18

invalid schema

stack:

goroutine 1 [running]:
github.com/kwilteam/kwil-db/cmd/kwild/server.New.func1()
	/home/jon/kwil/git/kwil-db/cmd/kwild/server/server.go:81 +0x24d
panic({0x173dfc0?, 0xc000693680?})
	/home/jon/go122/src/runtime/panic.go:770 +0x132
github.com/kwilteam/kwil-db/cmd/kwild/server.failBuild(...)
	/home/jon/kwil/git/kwil-db/cmd/kwild/server/build.go:910
github.com/kwilteam/kwil-db/cmd/kwild/server.buildEngine(0xc0000d0ae0, 0xc0006d6480)
	/home/jon/kwil/git/kwil-db/cmd/kwild/server/build.go:527 +0x6e5
github.com/kwilteam/kwil-db/cmd/kwild/server.buildServer(0xc0000d0ae0, 0xc0005e0060)
	/home/jon/kwil/git/kwil-db/cmd/kwild/server/build.go:176 +0x68
github.com/kwilteam/kwil-db/cmd/kwild/server.New({0x1bbcc60, 0xc000140050}, 0xc0003a86c0, 0xc00042b180, 0xc000516378, 0x0)
	/home/jon/kwil/git/kwil-db/cmd/kwild/server/server.go:120 +0xa09
github.com/kwilteam/kwil-db/cmd/kwild/root.RootCmd.func1(0xc00027a308, {0xc000157060?, 0x7?, 0x18613d2?})
	/home/jon/kwil/git/kwil-db/cmd/kwild/root/root.go:92 +0x573
github.com/spf13/cobra.(*Command).execute(0xc00027a308, {0xc000052520, 0x2, 0x2})
	/home/jon/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc00027a308)
	/home/jon/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0xc0000061c0?)
	/home/jon/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039 +0x13
main.main()
	/home/jon/kwil/git/kwil-db/cmd/kwild/main.go:10 +0x18
```

**Comment by jchappelow** [comment]
Resolved by https://github.com/kwilteam/kwil-db/pull/810
